# Generated by Django 5.2.5 on 2025-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_salon_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='salon',
            name='endT',
            field=models.CharField(default='17:00', max_length=100),
        ),
        migrations.AddField(
            model_name='salon',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='salon_images/'),
        ),
        migrations.AddField(
            model_name='salon',
            name='startT',
            field=models.CharField(default='09:00', max_length=100),
        ),
    ]
