# Generated by Django 5.2.5 on 2025-09-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_salon_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='salon',
            name='endT',
            field=models.CharField(default='17:00:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='salon',
            name='startT',
            field=models.CharField(default='09:00:00', max_length=100),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='salon_images/')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.salon')),
            ],
        ),
    ]
