# Generated by Django 5.2.5 on 2025-09-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
