# Generated by Django 5.2.5 on 2025-09-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
    ]
