# Generated by Django 5.2.5 on 2025-10-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
