# Generated by Django 5.2.5 on 2025-10-10 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_booking_status_alter_booking_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='api.salon')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.service'),
        ),
    ]
