# Generated by Django 5.2.5 on 2025-10-10 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_service_alter_booking_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='services',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='api.salon'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
