# Generated by Django 5.2.5 on 2025-10-12 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_booking_service_name_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services'),
        ),
    ]
