# Generated by Django 5.2.5 on 2025-10-15 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_booking_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_items', to='api.salon'),
        ),
    ]
