# Generated by Django 5.2.5 on 2025-10-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_services_salon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='service_name',
            new_name='service',
        ),
    ]
