# Generated by Django 5.2.5 on 2025-10-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_service_name_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
