# Generated by Django 5.2.5 on 2025-10-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('completed', 'Completed'), ('incomplete', 'Incomplete'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
